import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

declare global {
  var __INTEROCITOR_DOCS_ROOT__: string;
}

type DecisionPage = "trust" | "data-boundaries" | "mailbox" | "automation";
type DemoPage = "todomvc" | "chat" | "board" | "family-locator";

type Page = {
  source: string;
  output: string;
  header:
    | { kind: "home" }
    | { kind: "explainer" }
    | { kind: "decision"; current: DecisionPage }
    | { kind: "demo"; current: DemoPage; label: string; lightLogo?: boolean };
};

const HEADER_INCLUDE = '<!--#include virtual="/_includes/site-header.html" -->';
const FOOTER_INCLUDE = '<!--#include virtual="/_includes/site-footer.html" -->';
const GENERATED_NOTICE =
  "<!-- Generated by docs/site/build.ts; edit the matching docs/site/pages template. -->";

const pages: Page[] = [
  { source: "site/pages/index.html", output: "index.html", header: { kind: "home" } },
  {
    source: "site/pages/how-it-works.html",
    output: "how-it-works.html",
    header: { kind: "explainer" },
  },
  ...(["trust", "data-boundaries", "mailbox", "automation"] as const).map((current) => ({
    source: `site/pages/${current}.html`,
    output: `${current}.html`,
    header: { kind: "decision" as const, current },
  })),
  {
    source: "site/pages/examples/todomvc.html",
    output: "examples/todomvc/index.html",
    header: { kind: "demo", current: "todomvc", label: "Live local demo", lightLogo: true },
  },
  {
    source: "site/pages/examples/chat.html",
    output: "examples/chat/index.html",
    header: { kind: "demo", current: "chat", label: "Live encrypted demo" },
  },
  {
    source: "site/pages/examples/board.html",
    output: "examples/board/index.html",
    header: { kind: "demo", current: "board", label: "Live local-first board" },
  },
  {
    source: "site/pages/examples/family-locator.html",
    output: "examples/family-locator/index.html",
    header: { kind: "demo", current: "family-locator", label: "Protected-data demo" },
  },
];

const docsRoot = globalThis.__INTEROCITOR_DOCS_ROOT__;
const check = process.argv.includes("--check");

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function isDemo(page: Page): page is Page & { header: Extract<Page["header"], { kind: "demo" }> } {
  return page.header.kind === "demo";
}

function prefix(page: Page): string {
  return isDemo(page) ? "../../" : "";
}

function renderHeader(page: Page): string {
  const base = prefix(page);

  if (page.header.kind === "home") {
    return `<header class="site-header">
      <div class="shell nav">
        <a class="brand" href="#top" aria-label="Interocitor home">
          <img class="brand-logo" src="assets/hero-dark.svg" alt="Interocitor" />
        </a>
        <nav class="nav-links" aria-label="Primary navigation">
          <a href="#why">Why Interocitor</a>
          <a href="examples/todomvc/">Live TodoMVC</a>
          <a href="#decisions">Architecture guides</a>
          <a href="#security">Trust boundary</a>
        </nav>
        <a class="nav-cta" href="how-it-works.html">How it works <span aria-hidden="true">↗</span></a>
      </div>
    </header>`;
  }

  if (page.header.kind === "explainer") {
    return `<header class="site-header">
      <div class="shell nav">
        <a class="brand" href="index.html" aria-label="Interocitor home">
          <img class="brand-logo" src="assets/hero-dark.svg" alt="Interocitor" />
        </a>
        <nav class="nav-links" aria-label="How it works sections">
          <a href="#evolution">Two operators</a>
          <a href="#journey">One change</a>
          <a href="#compaction">100 changes</a>
          <a href="#boundary">The boundary</a>
          <a href="#protection">Access &amp; protection</a>
          <a href="#adapter-boundary">Storage choices</a>
        </nav>
        <a class="nav-cta" href="index.html#decisions">Architecture guides <span aria-hidden="true">↗</span></a>
      </div>
    </header>`;
  }

  if (page.header.kind === "decision") {
    const links: Array<[DecisionPage, string]> = [
      ["trust", "Trust"],
      ["data-boundaries", "Data shape"],
      ["mailbox", "Mailbox"],
      ["automation", "Automation"],
    ];
    const navigation = links
      .map(
        ([id, label]) =>
          `<a href="${id}.html"${id === page.header.current ? ' aria-current="page"' : ""}>${label}</a>`,
      )
      .join("\n          ");
    return `<header class="site-header">
      <div class="shell nav">
        <a class="brand" href="index.html" aria-label="Interocitor home">
          <img class="brand-logo" src="assets/hero-dark.svg" alt="Interocitor" />
        </a>
        <nav class="nav-links" aria-label="Decision guides">
          ${navigation}
        </nav>
        <a class="nav-cta" href="examples/todomvc/">Live TodoMVC <span aria-hidden="true">↗</span></a>
      </div>
    </header>`;
  }

  const logo = page.header.lightLogo ? "hero.svg" : "hero-dark.svg";
  return `<header class="site-header">
      <a href="${base}index.html" class="brand" aria-label="Interocitor home">
        <img class="brand-logo" src="${base}assets/${logo}" alt="Interocitor" />
      </a>
      <p><strong>${escapeHtml(page.header.label)}</strong> · nothing leaves this tab</p>
      <a href="${base}index.html" class="back-link">Overview <span aria-hidden="true">↗</span></a>
    </header>`;
}

function renderFooter(page: Page): string {
  const base = prefix(page);
  const demo = isDemo(page) ? page.header.current : null;
  const wrapper = isDemo(page) ? "" : "shell ";
  const demoLinks = [
    demo === "todomvc" ? "" : `<a href="${base}examples/todomvc/">Live TodoMVC</a>`,
    demo === "chat" ? "" : `<a href="${base}examples/chat/">Live encrypted chat</a>`,
    demo === "board" ? "" : `<a href="${base}examples/board/">Live shared board</a>`,
    demo === "family-locator"
      ? ""
      : `<a href="${base}examples/family-locator/">Protected family locator</a>`,
  ]
    .filter(Boolean)
    .join("\n            ");
  const demoNote = demo
    ? '<span class="footer-demo-note">Live demo · nothing leaves this tab</span>'
    : `<a class="footer-demo-link" href="${base}examples/todomvc/">Try the live TodoMVC <span aria-hidden="true">↗</span></a>`;
  const bottomNote =
    demo === "todomvc"
      ? "No account · no WebDAV · no cloud"
      : demo === "chat"
        ? "Two trusted clients · one protected mesh"
        : demo === "board"
          ? "Independent local edits · explicit convergence"
          : demo === "family-locator"
            ? "Protected payloads · not a safety service"
            : "Trusted endpoints · protected mailbox";

  return `<footer class="site-map-footer">
      <div class="${wrapper}site-map-footer-grid">
        <div class="site-map-brand">
          <a class="brand" href="${base}index.html" aria-label="Interocitor home">
            <img class="brand-logo" src="${base}assets/hero-dark.svg" alt="Interocitor" />
          </a>
          <p>Local-first application data without remote plaintext.</p>
          ${demoNote}
        </div>
        <nav class="site-map-nav" aria-label="Interocitor site map">
          <section>
            <h2>Explore</h2>
            <a href="${base}index.html">Overview</a>
            <a href="${base}how-it-works.html">How it works</a>
            ${demoLinks}
            <a href="https://github.com/Machine-Garden/interocitor/blob/main/packages/core/docs/security-model.md">Security model</a>
          </section>
          <section>
            <h2>Architecture guides</h2>
            <a href="${base}trust.html">Trust &amp; keys</a>
            <a href="${base}data-boundaries.html">Rows, files &amp; scale</a>
            <a href="${base}mailbox.html">Mailbox operations</a>
            <a href="${base}automation.html">Trusted automation</a>
          </section>
          <section>
            <h2>Build</h2>
            <a href="https://github.com/Machine-Garden/interocitor/tree/main/packages/web#readme">Browser apps</a>
            <a href="https://github.com/Machine-Garden/interocitor/tree/main/packages/workers#readme">Cloudflare mailbox</a>
            <a href="https://github.com/Machine-Garden/interocitor/tree/main/examples">Examples</a>
            <a href="https://github.com/Machine-Garden/interocitor">Source on GitHub</a>
          </section>
        </nav>
      </div>
      <div class="${wrapper}site-map-bottom">
        <span>Interocitor · MIT licensed</span>
        <span>${bottomNote}</span>
      </div>
    </footer>`;
}

function renderPage(template: string, page: Page): string {
  const headerIncludes = template.split(HEADER_INCLUDE).length - 1;
  const footerIncludes = template.split(FOOTER_INCLUDE).length - 1;
  if (headerIncludes !== 1 || footerIncludes !== 1) {
    throw new Error(
      `${page.source} must include exactly one shared site header and footer directive`,
    );
  }
  if (/class\s*=\s*["'][^"']*\b(?:site-header|site-map-footer)\b[^"']*["']/i.test(template)) {
    throw new Error(`${page.source} must not define site chrome directly`);
  }

  return template
    .replace("<!doctype html>", `<!doctype html>\n${GENERATED_NOTICE}`)
    .replace(HEADER_INCLUDE, renderHeader(page))
    .replace(FOOTER_INCLUDE, renderFooter(page));
}

const stale: string[] = [];
for (const page of pages) {
  const sourcePath = resolve(docsRoot, page.source);
  const outputPath = resolve(docsRoot, page.output);
  const expected = renderPage(await readFile(sourcePath, "utf8"), page);

  if (check) {
    const actual = await readFile(outputPath, "utf8").catch(() => "");
    if (actual !== expected) stale.push(page.output);
    continue;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, expected);
}

if (stale.length > 0) {
  throw new Error(`Generated site pages are stale: ${stale.join(", ")}. Run yarn build:docs:site`);
}
