export { IndexedDbLocalStore } from "./storage/indexed-db-local-store.ts";
export {
  createResilientLocalStore,
  DEFAULT_LOCAL_OPEN_TIMEOUT_MS,
  type ResilientLocalStoreOptions,
  type LocalStoreDegradedHook,
  type LocalStoreDegradationInfo,
  type LocalStoreDegradationReason,
} from "./storage/resilient-store.ts";
export {
  createNamedLocalStore,
  getActiveLocalDatabaseName,
  isGeneratedLocalDatabaseName,
  rotateLocalDatabaseName,
  type NamedLocalStore,
  type NamedLocalStoreOptions,
  type PointerStore,
} from "./storage/named-local-store.ts";
export {
  resetLocalDatabase,
  resetLocalDatabaseWithDeadline,
  type ResetLocalDatabaseOutcome,
} from "./storage/reset.ts";

export {
  WebAuthnBlobStore,
  type WebAuthnAttachmentPreference,
  type WebAuthnBlobStoreOptions,
  type WebAuthnCredentialRef,
  type WebAuthnEnrollOptions,
  type WebAuthnLoadOptions,
  CredentialAccessError,
  CredentialUnavailableError,
  CredentialUnreadableError,
  ResidualWebAuthnCredentialError,
  credentialAvailabilityOf,
  isCredentialAccessError,
  type CredentialAccessErrorInit,
  type CredentialAvailability,
  type WebAuthnBlobFormat,
  type WebAuthnClearOptions,
  type WebAuthnClearResult,
  type WebAuthnResidualRisk,
  type WebAuthnTaggedBlob,
} from "./webauthn.ts";

export {
  BrowserStorageSecretStore,
  WebAuthnCrossPlatformSecretStore,
  WebAuthnPlatformSecretStore,
  createWebSecretStore,
  type CreateWebSecretStoreOptions,
  type WebAuthnSecretStore,
  type WebSecretCustody,
  type WebSecretStore,
} from "./secret-store.ts";

export {
  BrowserCredentialEnvelopeStore,
  EnvelopedCredentialStore,
  LocalStorageCredentialStore,
  MemoryCredentialEnvelopeStore,
  MemoryCredentialStore,
  SessionStorageCredentialStore,
  StaticEnvelopeKeyProvider,
  WebAuthnCredentialStore,
  WebAuthnEnvelopeKeyProvider,
  UnstableCredentialNamespaceError,
  createWebCredentialStore,
  type CreateWebCredentialStoreOptions,
  type CredentialEnvelopeKeyProvider,
  type CredentialEnvelopeKeyPurpose,
  type CredentialEnvelopeStore,
  type CredentialStorageLocation,
  type EnvelopeStorageLocation,
  type WebCredentialStore,
  CURRENT_CREDENTIAL_ENVELOPE_VERSION,
  type CredentialEnvelopeKeyRequest,
  type StoredCredentialEnvelope,
  type StoredCredentialEnvelopeV1,
  type StoredCredentialEnvelopeV2,
} from "./credential-store.ts";

export {
  putImage,
  getImage,
  getImageBlobUrl,
  type ImageInput,
  type PutImageOptions,
  type StoredImage,
  type StoredImageBlobUrl,
  type StoredImageMetadata,
} from "./image.ts";

export {
  BrowserPassphraseKeyRecordStore,
  MemoryPassphraseKeyRecordStore,
  PassphraseEnvelopeKeyProvider,
  PassphraseEnvelopeError,
  PassphraseLockedError,
  PassphraseNamespaceMismatchError,
  InvalidPassphraseKeyRecordError,
  MissingPassphraseKeyRecordError,
  WrongPassphraseError,
  isPassphraseEnvelopeError,
  type PassphraseEnvelopeErrorCode,
  DEFAULT_PASSPHRASE_IDLE_TIMEOUT_MS,
  DEFAULT_PASSPHRASE_KDF_ITERATIONS,
  MAXIMUM_PASSPHRASE_KDF_ITERATIONS,
  MINIMUM_PASSPHRASE_KDF_ITERATIONS,
  type PassphraseEnvelopeKeyProviderOptions,
  type PassphraseKeyRecord,
  type PassphraseKeyRecordStore,
  type PassphraseRecordStorageLocation,
} from "./passphrase-envelope.ts";
