/**
 * @interocitor/core/handshake/qr
 *
 * QR code payload encoding and decoding for the handshake protocol.
 *
 * ## Two intents
 *
 * A QR code is always generated by one device and scanned by another.
 * The intent declares what the QR *generator* wants:
 *
 *   "share" — I already belong to a mesh. Scan me: I will push
 *             remotePath + passphrase to you via the relay.
 *
 *   "join"  — I want to join a mesh. Scan me: push your mesh
 *             credentials to me via the relay.
 *
 * For "share", the generator sends the encrypted credentials and the scanner
 * receives them. For "join", the scanner sends the encrypted credentials and
 * the generator receives them. Both sides publish relay artifacts as part of
 * the ephemeral ECDH exchange.
 *
 * ## Two pieces in the QR
 *
 *   Cloud piece  →  handshakeId
 *                   Scopes two relay files on the shared backend. Polling
 *                   defaults to a 120,000 ms timeout and cleanup is
 *                   best-effort. Anyone with cloud access can see these
 *                   files — but cannot decrypt them (see below).
 *
 *   Invitation   →  generatorPub (ephemeral ECDH-P256 public key)
 *                   Used by the scanner to derive a wrapping key via
 *                   ECDH. The corresponding private key never leaves
 *                   the generating device. Treat the complete QR or pair-link
 *                   payload as a short-lived invitation capability: anyone
 *                   who obtains it and can reach the relay can act as the
 *                   scanner. Relay access alone is insufficient to derive the
 *                   wrapping key.
 *
 * ## What is NOT in the QR
 *
 *   remotePath   — travels via the relay only, encrypted with the
 *                  ECDH-derived wrapping key.
 *   passphrase   — same; null identifies an unencrypted mesh.
 *
 * ## Encoding
 *
 * The payload is a compact base64url JSON string, safe to embed in a
 * URL fragment (never reaches any server):
 *
 *   https://yourapp.com/pair#hs=<base64url>
 */

export type HandshakeIntent = "share" | "join";

export interface HandshakeQRPayload {
  /**
   * Intent of the QR *generator*:
   *   "share" → generator has the mesh credentials and will push them.
   *   "join"  → generator wants credentials pushed to it.
   */
  intent: HandshakeIntent;
  /**
   * Random hex string scoping the relay files on the shared backend.
   * This is the "cloud piece" — visible to anyone with backend access,
   * but useless without the generator's ephemeral ECDH private key.
   */
  handshakeId: string;
  /**
   * Generator's ephemeral ECDH-P256 public key, base64url-encoded SPKI.
   * This is the invitation piece. It may arrive through a scanned QR or a
   * copied pair URL. The scanner uses it to derive the shared wrapping key.
   */
  generatorPub: string;
  /**
   * Opaque backend connection config produced by adapter.getHandshakeConfig().
   *
   * Tells the scanner how to reach the same backend as the generator so
   * they can exchange relay files. Must NOT contain credentials.
   *
   * Present for adapters where the backend address is not known to the app
   * in advance (WebDAV, Google Drive, sharded CF workers, …).
   * Absent when the backend is fixed and app-global (e.g. a single CF worker
   * whose URL is baked into the binary).
   *
   * The application uses this value to construct/authenticate the matching
   * adapter, or handles it through the high-level `adapterFromConfig`
   * callback, before starting the relay exchange.
   */
  adapterConfig?: string;
}

/** Encode a HandshakeQRPayload to a compact URL-safe base64 string. */
export function encodeQRPayload(payload: HandshakeQRPayload): string {
  const json = JSON.stringify(payload);
  const bytes = new TextEncoder().encode(json);
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCodePoint(bytes[i]);
  }
  return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
}

/** Decode a compact URL-safe base64 string back to HandshakeQRPayload. */
export function decodeQRPayload(encoded: string): HandshakeQRPayload {
  const padded = encoded.replaceAll("-", "+").replaceAll("_", "/");
  const pad = (4 - (padded.length % 4)) % 4;
  const b64 = padded + "=".repeat(pad);

  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.codePointAt(i)!;
  }
  const json = new TextDecoder().decode(bytes);
  const payload = JSON.parse(json) as HandshakeQRPayload;

  if (
    (payload.intent !== "share" && payload.intent !== "join") ||
    typeof payload.handshakeId !== "string" ||
    typeof payload.generatorPub !== "string" ||
    (payload.adapterConfig !== undefined && typeof payload.adapterConfig !== "string")
  ) {
    throw new Error("Invalid handshake QR payload");
  }

  return payload;
}

/**
 * Build a full join URL with the handshake payload in the fragment.
 * The fragment is never sent to any server.
 */
export function buildPairUrl(baseUrl: string, payload: HandshakeQRPayload): string {
  const encoded = encodeQRPayload(payload);
  const base = baseUrl.replace(/#.*$/, "");
  return `${base}#hs=${encoded}`;
}

/**
 * Extract and decode a HandshakeQRPayload from a URL fragment string.
 * Pass the URL fragment string directly.
 * Returns null if no #hs= fragment is present.
 */
export function parseQRFromUrl(hash: string): HandshakeQRPayload | null {
  const match = hash.match(/(?:^|[#&])hs=([A-Za-z0-9_-]+)/);
  if (!match) return null;
  try {
    return decodeQRPayload(match[1]);
  } catch {
    return null;
  }
}
